# Generated by Django 5.0.6 on 2024-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraAplicacion', '0003_publisher_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('brith_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='PrimeraAplicacion.author'),
        ),
    ]
