# Generated by Django 5.0.6 on 2024-07-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraAplicacion', '0004_author_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
